### ISSUE TITLE
cdu supports YAML configuration

### ISSUE THREAD

**Issue by henry40408** [henry40408/mono-rs#63]
- https://github.com/dtolnay/serde-yaml

```yaml
zone: example.com
records:
- record: *
- record: www
- record: dns
```
